# src/AppBundle/Resources/config/routing.yml

app_home:
    path:    /
    defaults:
        _controller: AppBundle:Louvre:index

app_booking:
    path:    /booking
    defaults:
        _controller: AppBundle:Louvre:booking

