# src/OC/PlatformBundle/Resources/config/services.yml

services:
    oc_platform.antispam:
        class:  OC\PlatformBundle\Antispam\OCAntispam
        arguments:
          - "@mailer"
          - "%locale%"
          - 50

    oc_platform.email.application_mailer:
        class: OC\PlatformBundle\Email\ApplicationMailer
        arguments:
          - "@mailer"

    oc_platform.doctrine_listener.application_creation:
        class:  OC\PlatformBundle\DoctrineListener\ApplicationCreationListener
        arguments:
          - "@oc_platform.email.application_mailer"
        tags:
          - { name: doctrine.event_listener, event: postPersist }

    oc_platform.purger.advert:
        class:  OC\PlatformBundle\Purger\PurgerAdvert
        arguments:
          - "@doctrine.orm.entity_manager"

    oc_platform.validator.antiflood:
        class: OC\PlatformBundle\Validator\AntifloodValidator
        arguments: ["@request_stack", "@doctrine.orm.entity_manager"] #Les données que l'on injecte au service: la requête et l'EntityManager
        tags:
          - { name: validator.constraint_validator, alias: oc_platform_antiflood } #C'est avec l'alias que l'on retrouvera le service

    oc_platform.twig.antispam_extension:
        class: OC\PlatformBundle\Twig\AntispamExtension
        arguments:
          - "@oc_platform.antispam"
        tags:
         - { name: twig.extension }

    oc_platform.form.ckeditor:
        class: Ivory\CKEditorBundle\Command\CKEditorInstallerCommand
        tags:
         - { name: form.type, alias: ckeditor }

    oc_platform.beta.listener:
        class: OC\PlatformBundle\Beta\BetaListener
        arguments:
            - "@oc_platform.beta.html_adder"
            - "2017-11-09"
        tags:
          - { name: kernel.event_listener, event: kernel.response, method: processBeta }

    oc_platform.beta.html_adder:
        class: OC\PlatformBundle\Beta\BetaHTMLAdder

    oc_platform.bigbrother.message_notificator:
        class: OC\PlatformBundle\Bigbrother\MessageNotificator
        arguments:
         - "@mailer"

    oc_platform.bigbrother.message_listener:
        class: OC\PlatformBundle\Bigbrother\MessageListener
        arguments:
         - "@oc_platform.bigbrother.message_notificator"
         - ["alexandre", "Marine", "pierre"]
        tags:
         - { name: kernel.event_listener, event: oc_platform.post_message, method: processMessage }



